### ISSUE TITLE
Nobody listens to me.

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-fundamentals-starter-apps-v2#6]
In doing whatever Gradle on Android Studio 3.5.3 does, the failure reports:

ERROR: Unsupported method: AndroidProject.getVariantNames(). The version of Gradle you connect to does not support that method. To resolve the problem you can change/upgrade the target version of Gradle you connect to. Alternatively, you can ignore this exception and read other information from the model.

You can't expect new users to deal with that.

**Comment by Kha3Leng** [comment]
Thank you
